name: Run dbt models

on:
  push:
    branches:
      - main # The workflow runs on pushes to the main branch
  
  # Allow you to run the workflow manually from action tab
  workflow_dispatch:

jobs:
  run_dbt_models:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      DBT_PROFILES_DIR: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify the Python version

      - name: Install dbt and snowflake adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake
      - name: Create dbt profile.yml
        run: |
          echo "snow_dbt_pipeline:" > profiles.yml
          echo "  target: prod" >> profiles.yml
          echo "  outputs:" >> profiles.yml
          echo "    prod:" >> profiles.yml
          echo "      type: snowflake" >> profiles.yml
          echo "      account: $SNOWFLAKE_ACCOUNT" >> profiles.yml
          echo "      user: $SNOWFLAKE_USER" >> profiles.yml
          echo "      password: $SNOWFLAKE_PASSWORD" >> profiles.yml
          echo "      role: $SNOWFLAKE_ROLE" >> profiles.yml
          echo "      database: $SNOWFLAKE_DATABASE" >> profiles.yml
          echo "      warehouse: $SNOWFLAKE_WAREHOUSE" >> profiles.yml
          echo "      schema: $SNOWFLAKE_SCHEMA" >> profiles.yml
          echo "      threads: 4" >> profiles.yml

      - name: Run dbt dependencies and models
        run: |
          dbt deps  
          dbt run --target prod

      - name: Run dbt tests
        run: dbt test --target prod
            
