name: Scheduled - Hourly Revenue Run

on:
  schedule:
    # Runs every hour at the top of the hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run_dim_customers:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      DBT_PROFILES_DIR: .

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dbt and Snowflake adapter
        run: pip install dbt-snowflake
      - name: Create dbt profiles.yml
        run: |
          echo "snow_dbt_pipeline:" > profiles.yml
          echo "  target: prod" >> profiles.yml
          echo "  outputs:" >> profiles.yml
          echo "    prod:" >> profiles.yml
          echo "      type: snowflake" >> profiles.yml
          echo "      account: $SNOWFLAKE_ACCOUNT" >> profiles.yml
          echo "      user: $SNOWFLAKE_USER" >> profiles.yml
          echo "      password: $SNOWFLAKE_PASSWORD" >> profiles.yml
          echo "      role: $SNOWFLAKE_ROLE" >> profiles.yml
          echo "      database: $SNOWFLAKE_DATABASE" >> profiles.yml
          echo "      warehouse: $SNOWFLAKE_WAREHOUSE" >> profiles.yml
          echo "      schema: $SNOWFLAKE_SCHEMA" >> profiles.yml 
          echo "      threads: 4" >> profiles.yml
      - name: Run dbt dependencies
        run: dbt deps
      - name: Run hourly revenue model
        # Use --select to target only the model we want to run
        run: dbt run --select dim_customers --target prod
